services:
  evilginx:
    build: .
    image: evilginx2:latest
    container_name: evilginx2
    restart: unless-stopped

    tty: true
    stdin_open: true

    network_mode: host

    environment:
      - TZ=${TZ:-UTC}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN:-}
      - TG_CHAT_ID=${TG_CHAT_ID:-}

    volumes:
      - ./phishlets:/app/phishlets
      - ./sessions:/app/sessions
      - ./certs:/app/certs
